//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempleLDAPEntry", Namespace="http://wsw.temple.edu/")]
    public partial class TempleLDAPEntry : object
    {
        
        private string templeEduTUIDField;
        
        private string cnField;
        
        private string givenNameField;
        
        private string snField;
        
        private string uidField;
        
        private string eduPersonAffiliationField;
        
        private string eduPersonPrimaryAffiliationField;
        
        private string titleField;
        
        private string mailField;
        
        private string errorField;
        
        private string creatorsNameField;
        
        private string displayNameField;
        
        private string gidNumberField;
        
        private string homeDirectoryField;
        
        private string lField;
        
        private string loginShellField;
        
        private string mailAlternateAddressField;
        
        private string mailHostField;
        
        private string mailRoutingAddressField;
        
        private ServiceReference1.ManagerLDAPEntry managerField;
        
        private string modifiersNameField;
        
        private string modifyTimestampField;
        
        private string oField;
        
        private string objectClassField;
        
        private string ouField;
        
        private string postOfficeBoxField;
        
        private string postalAddressField;
        
        private string telephoneNumberField;
        
        private string templeEduAccountField;
        
        private string templeEduDateOfBirthField;
        
        private string templeEduDepartmentPhoneField;
        
        private string templeEduEmployeeDepartmentField;
        
        private string templeEduEmployeeDepartmentCodeField;
        
        private string templeEduGivenNameField;
        
        private string templeEduJobClassField;
        
        private string templeEduNamePrefixField;
        
        private string templeEduOrganizationCodeField;
        
        private string templeEduPrimaryOUField;
        
        private string templeEduPrimaryOUCodeField;
        
        private string templeEduSNField;
        
        private string templeEduTUCountryField;
        
        private string templeEduTUNAField;
        
        private string templeEduTUNICField;
        
        private string templeEduTUStPrField;
        
        private string templeEduTUStreetField;
        
        private string templeEduTUZPCField;
        
        private string templeEduWorkPhoneField;
        
        private string uidNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string templeEduTUID
        {
            get
            {
                return this.templeEduTUIDField;
            }
            set
            {
                this.templeEduTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cn
        {
            get
            {
                return this.cnField;
            }
            set
            {
                this.cnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string givenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sn
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string eduPersonAffiliation
        {
            get
            {
                return this.eduPersonAffiliationField;
            }
            set
            {
                this.eduPersonAffiliationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eduPersonPrimaryAffiliation
        {
            get
            {
                return this.eduPersonPrimaryAffiliationField;
            }
            set
            {
                this.eduPersonPrimaryAffiliationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string creatorsName
        {
            get
            {
                return this.creatorsNameField;
            }
            set
            {
                this.creatorsNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string gidNumber
        {
            get
            {
                return this.gidNumberField;
            }
            set
            {
                this.gidNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string homeDirectory
        {
            get
            {
                return this.homeDirectoryField;
            }
            set
            {
                this.homeDirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string l
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string loginShell
        {
            get
            {
                return this.loginShellField;
            }
            set
            {
                this.loginShellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string mailAlternateAddress
        {
            get
            {
                return this.mailAlternateAddressField;
            }
            set
            {
                this.mailAlternateAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string mailHost
        {
            get
            {
                return this.mailHostField;
            }
            set
            {
                this.mailHostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string mailRoutingAddress
        {
            get
            {
                return this.mailRoutingAddressField;
            }
            set
            {
                this.mailRoutingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public ServiceReference1.ManagerLDAPEntry manager
        {
            get
            {
                return this.managerField;
            }
            set
            {
                this.managerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string modifiersName
        {
            get
            {
                return this.modifiersNameField;
            }
            set
            {
                this.modifiersNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string modifyTimestamp
        {
            get
            {
                return this.modifyTimestampField;
            }
            set
            {
                this.modifyTimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string o
        {
            get
            {
                return this.oField;
            }
            set
            {
                this.oField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string objectClass
        {
            get
            {
                return this.objectClassField;
            }
            set
            {
                this.objectClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string ou
        {
            get
            {
                return this.ouField;
            }
            set
            {
                this.ouField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string postOfficeBox
        {
            get
            {
                return this.postOfficeBoxField;
            }
            set
            {
                this.postOfficeBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string postalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string telephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string templeEduAccount
        {
            get
            {
                return this.templeEduAccountField;
            }
            set
            {
                this.templeEduAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string templeEduDateOfBirth
        {
            get
            {
                return this.templeEduDateOfBirthField;
            }
            set
            {
                this.templeEduDateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string templeEduDepartmentPhone
        {
            get
            {
                return this.templeEduDepartmentPhoneField;
            }
            set
            {
                this.templeEduDepartmentPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string templeEduEmployeeDepartment
        {
            get
            {
                return this.templeEduEmployeeDepartmentField;
            }
            set
            {
                this.templeEduEmployeeDepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string templeEduEmployeeDepartmentCode
        {
            get
            {
                return this.templeEduEmployeeDepartmentCodeField;
            }
            set
            {
                this.templeEduEmployeeDepartmentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string templeEduGivenName
        {
            get
            {
                return this.templeEduGivenNameField;
            }
            set
            {
                this.templeEduGivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string templeEduJobClass
        {
            get
            {
                return this.templeEduJobClassField;
            }
            set
            {
                this.templeEduJobClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string templeEduNamePrefix
        {
            get
            {
                return this.templeEduNamePrefixField;
            }
            set
            {
                this.templeEduNamePrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string templeEduOrganizationCode
        {
            get
            {
                return this.templeEduOrganizationCodeField;
            }
            set
            {
                this.templeEduOrganizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string templeEduPrimaryOU
        {
            get
            {
                return this.templeEduPrimaryOUField;
            }
            set
            {
                this.templeEduPrimaryOUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string templeEduPrimaryOUCode
        {
            get
            {
                return this.templeEduPrimaryOUCodeField;
            }
            set
            {
                this.templeEduPrimaryOUCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string templeEduSN
        {
            get
            {
                return this.templeEduSNField;
            }
            set
            {
                this.templeEduSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string templeEduTUCountry
        {
            get
            {
                return this.templeEduTUCountryField;
            }
            set
            {
                this.templeEduTUCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string templeEduTUNA
        {
            get
            {
                return this.templeEduTUNAField;
            }
            set
            {
                this.templeEduTUNAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string templeEduTUNIC
        {
            get
            {
                return this.templeEduTUNICField;
            }
            set
            {
                this.templeEduTUNICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string templeEduTUStPr
        {
            get
            {
                return this.templeEduTUStPrField;
            }
            set
            {
                this.templeEduTUStPrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string templeEduTUStreet
        {
            get
            {
                return this.templeEduTUStreetField;
            }
            set
            {
                this.templeEduTUStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string templeEduTUZPC
        {
            get
            {
                return this.templeEduTUZPCField;
            }
            set
            {
                this.templeEduTUZPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=46)]
        public string templeEduWorkPhone
        {
            get
            {
                return this.templeEduWorkPhoneField;
            }
            set
            {
                this.templeEduWorkPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=47)]
        public string uidNumber
        {
            get
            {
                return this.uidNumberField;
            }
            set
            {
                this.uidNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManagerLDAPEntry", Namespace="http://wsw.temple.edu/")]
    public partial class ManagerLDAPEntry : object
    {
        
        private string templeEduTUIDField;
        
        private string cnField;
        
        private string givenNameField;
        
        private string snField;
        
        private string uidField;
        
        private string eduPersonAffiliationField;
        
        private string eduPersonPrimaryAffiliationField;
        
        private string titleField;
        
        private string mailField;
        
        private string creatorsNameField;
        
        private string displayNameField;
        
        private string gidNumberField;
        
        private string homeDirectoryField;
        
        private string lField;
        
        private string loginShellField;
        
        private string mailAlternateAddressField;
        
        private string mailHostField;
        
        private string mailRoutingAddressField;
        
        private string modifiersNameField;
        
        private string modifyTimestampField;
        
        private string oField;
        
        private string objectClassField;
        
        private string ouField;
        
        private string postOfficeBoxField;
        
        private string postalAddressField;
        
        private string telephoneNumberField;
        
        private string templeEduAccountField;
        
        private string templeEduDateOfBirthField;
        
        private string templeEduDepartmentPhoneField;
        
        private string templeEduEmployeeDepartmentField;
        
        private string templeEduEmployeeDepartmentCodeField;
        
        private string templeEduGivenNameField;
        
        private string templeEduJobClassField;
        
        private string templeEduNamePrefixField;
        
        private string templeEduOrganizationCodeField;
        
        private string templeEduPrimaryOUField;
        
        private string templeEduPrimaryOUCodeField;
        
        private string templeEduSNField;
        
        private string templeEduTUCountryField;
        
        private string templeEduTUNAField;
        
        private string templeEduTUNICField;
        
        private string templeEduTUStPrField;
        
        private string templeEduTUStreetField;
        
        private string templeEduTUZPCField;
        
        private string templeEduWorkPhoneField;
        
        private string uidNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string templeEduTUID
        {
            get
            {
                return this.templeEduTUIDField;
            }
            set
            {
                this.templeEduTUIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cn
        {
            get
            {
                return this.cnField;
            }
            set
            {
                this.cnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string givenName
        {
            get
            {
                return this.givenNameField;
            }
            set
            {
                this.givenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sn
        {
            get
            {
                return this.snField;
            }
            set
            {
                this.snField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string uid
        {
            get
            {
                return this.uidField;
            }
            set
            {
                this.uidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string eduPersonAffiliation
        {
            get
            {
                return this.eduPersonAffiliationField;
            }
            set
            {
                this.eduPersonAffiliationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string eduPersonPrimaryAffiliation
        {
            get
            {
                return this.eduPersonPrimaryAffiliationField;
            }
            set
            {
                this.eduPersonPrimaryAffiliationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string mail
        {
            get
            {
                return this.mailField;
            }
            set
            {
                this.mailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string creatorsName
        {
            get
            {
                return this.creatorsNameField;
            }
            set
            {
                this.creatorsNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string gidNumber
        {
            get
            {
                return this.gidNumberField;
            }
            set
            {
                this.gidNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string homeDirectory
        {
            get
            {
                return this.homeDirectoryField;
            }
            set
            {
                this.homeDirectoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string l
        {
            get
            {
                return this.lField;
            }
            set
            {
                this.lField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string loginShell
        {
            get
            {
                return this.loginShellField;
            }
            set
            {
                this.loginShellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string mailAlternateAddress
        {
            get
            {
                return this.mailAlternateAddressField;
            }
            set
            {
                this.mailAlternateAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string mailHost
        {
            get
            {
                return this.mailHostField;
            }
            set
            {
                this.mailHostField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string mailRoutingAddress
        {
            get
            {
                return this.mailRoutingAddressField;
            }
            set
            {
                this.mailRoutingAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string modifiersName
        {
            get
            {
                return this.modifiersNameField;
            }
            set
            {
                this.modifiersNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string modifyTimestamp
        {
            get
            {
                return this.modifyTimestampField;
            }
            set
            {
                this.modifyTimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string o
        {
            get
            {
                return this.oField;
            }
            set
            {
                this.oField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string objectClass
        {
            get
            {
                return this.objectClassField;
            }
            set
            {
                this.objectClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string ou
        {
            get
            {
                return this.ouField;
            }
            set
            {
                this.ouField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string postOfficeBox
        {
            get
            {
                return this.postOfficeBoxField;
            }
            set
            {
                this.postOfficeBoxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string postalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string telephoneNumber
        {
            get
            {
                return this.telephoneNumberField;
            }
            set
            {
                this.telephoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string templeEduAccount
        {
            get
            {
                return this.templeEduAccountField;
            }
            set
            {
                this.templeEduAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string templeEduDateOfBirth
        {
            get
            {
                return this.templeEduDateOfBirthField;
            }
            set
            {
                this.templeEduDateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string templeEduDepartmentPhone
        {
            get
            {
                return this.templeEduDepartmentPhoneField;
            }
            set
            {
                this.templeEduDepartmentPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public string templeEduEmployeeDepartment
        {
            get
            {
                return this.templeEduEmployeeDepartmentField;
            }
            set
            {
                this.templeEduEmployeeDepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string templeEduEmployeeDepartmentCode
        {
            get
            {
                return this.templeEduEmployeeDepartmentCodeField;
            }
            set
            {
                this.templeEduEmployeeDepartmentCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public string templeEduGivenName
        {
            get
            {
                return this.templeEduGivenNameField;
            }
            set
            {
                this.templeEduGivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string templeEduJobClass
        {
            get
            {
                return this.templeEduJobClassField;
            }
            set
            {
                this.templeEduJobClassField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string templeEduNamePrefix
        {
            get
            {
                return this.templeEduNamePrefixField;
            }
            set
            {
                this.templeEduNamePrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string templeEduOrganizationCode
        {
            get
            {
                return this.templeEduOrganizationCodeField;
            }
            set
            {
                this.templeEduOrganizationCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string templeEduPrimaryOU
        {
            get
            {
                return this.templeEduPrimaryOUField;
            }
            set
            {
                this.templeEduPrimaryOUField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=36)]
        public string templeEduPrimaryOUCode
        {
            get
            {
                return this.templeEduPrimaryOUCodeField;
            }
            set
            {
                this.templeEduPrimaryOUCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=37)]
        public string templeEduSN
        {
            get
            {
                return this.templeEduSNField;
            }
            set
            {
                this.templeEduSNField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=38)]
        public string templeEduTUCountry
        {
            get
            {
                return this.templeEduTUCountryField;
            }
            set
            {
                this.templeEduTUCountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=39)]
        public string templeEduTUNA
        {
            get
            {
                return this.templeEduTUNAField;
            }
            set
            {
                this.templeEduTUNAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=40)]
        public string templeEduTUNIC
        {
            get
            {
                return this.templeEduTUNICField;
            }
            set
            {
                this.templeEduTUNICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=41)]
        public string templeEduTUStPr
        {
            get
            {
                return this.templeEduTUStPrField;
            }
            set
            {
                this.templeEduTUStPrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=42)]
        public string templeEduTUStreet
        {
            get
            {
                return this.templeEduTUStreetField;
            }
            set
            {
                this.templeEduTUStreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=43)]
        public string templeEduTUZPC
        {
            get
            {
                return this.templeEduTUZPCField;
            }
            set
            {
                this.templeEduTUZPCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=44)]
        public string templeEduWorkPhone
        {
            get
            {
                return this.templeEduWorkPhoneField;
            }
            set
            {
                this.templeEduWorkPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=45)]
        public string uidNumber
        {
            get
            {
                return this.uidNumberField;
            }
            set
            {
                this.uidNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsw.temple.edu/", ConfigurationName="ServiceReference1.LDAP_SearchSoap")]
    public interface LDAP_SearchSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wsw.temple.edu/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.SearchResponse> SearchAsync(ServiceReference1.SearchRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Search", Namespace="http://wsw.temple.edu/", Order=0)]
        public ServiceReference1.SearchRequestBody Body;
        
        public SearchRequest()
        {
        }
        
        public SearchRequest(ServiceReference1.SearchRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsw.temple.edu/")]
    public partial class SearchRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string attribute;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string value;
        
        public SearchRequestBody()
        {
        }
        
        public SearchRequestBody(string username, string password, string attribute, string value)
        {
            this.username = username;
            this.password = password;
            this.attribute = attribute;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchResponse", Namespace="http://wsw.temple.edu/", Order=0)]
        public ServiceReference1.SearchResponseBody Body;
        
        public SearchResponse()
        {
        }
        
        public SearchResponse(ServiceReference1.SearchResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://wsw.temple.edu/")]
    public partial class SearchResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceReference1.TempleLDAPEntry[] SearchResult;
        
        public SearchResponseBody()
        {
        }
        
        public SearchResponseBody(ServiceReference1.TempleLDAPEntry[] SearchResult)
        {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface LDAP_SearchSoapChannel : ServiceReference1.LDAP_SearchSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class LDAP_SearchSoapClient : System.ServiceModel.ClientBase<ServiceReference1.LDAP_SearchSoap>, ServiceReference1.LDAP_SearchSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LDAP_SearchSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LDAP_SearchSoapClient.GetBindingForEndpoint(endpointConfiguration), LDAP_SearchSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LDAP_SearchSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LDAP_SearchSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LDAP_SearchSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LDAP_SearchSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LDAP_SearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.SearchResponse> ServiceReference1.LDAP_SearchSoap.SearchAsync(ServiceReference1.SearchRequest request)
        {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SearchResponse> SearchAsync(string username, string password, string attribute, string value)
        {
            ServiceReference1.SearchRequest inValue = new ServiceReference1.SearchRequest();
            inValue.Body = new ServiceReference1.SearchRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.attribute = attribute;
            inValue.Body.value = value;
            return ((ServiceReference1.LDAP_SearchSoap)(this)).SearchAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LDAP_SearchSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LDAP_SearchSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LDAP_SearchSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://preprod-wsw.temple.edu/ws_ldapsearch/ldap_search.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LDAP_SearchSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://preprod-wsw.temple.edu/ws_ldapsearch/ldap_search.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LDAP_SearchSoap,
            
            LDAP_SearchSoap12,
        }
    }
}
